server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


#  zipkin:
#    base-url: http://localhost:9411/

#actuator settings
management:
  health.circuitbreakers.enabled: true
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  tracing:
    sampling:
      probability: 1.0


resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 25
        eventConsumerBufferSize: 10
  timelimiter:
    instances:
      payment-service:
        timeoutDuration: 2000ms  # Maximum duration for method execution
        cancelRunningFuture: true  # Cancel the running task if timeout occurs



logging:
  level:
    root: INFO



